### ISSUE TITLE
node-ssh putfile报错

### ISSUE THREAD

**Issue by tanwenchao** [dashnowords/blogs#1]
文件传输异常: { Error: Failure
    at SFTPStream._transform (D:\upload\node_modules\_ssh2-streams@0.4.7@ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (D:\upload\node_modules\_ssh2-streams@0.4.7@ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:666:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12) code: 4, lang: '' }

**Comment by dashnowords** [comment]
> 文件传输异常: { Error: Failure
> at SFTPStream._transform (D:\upload\node_modules_ssh2-streams@0.4.7@ssh2-streams\lib\sftp.js:412:27)
> at SFTPStream.Transform._read (_stream_transform.js:190:10)
> at SFTPStream._read (D:\upload\node_modules_ssh2-streams@0.4.7@ssh2-streams\lib\sftp.js:183:15)
> at SFTPStream.Transform._write (_stream_transform.js:178:12)
> at doWrite (_stream_writable.js:410:12)
> at writeOrBuffer (_stream_writable.js:394:5)
> at SFTPStream.Writable.write (_stream_writable.js:294:11)
> at Channel.ondata (_stream_readable.js:666:20)
> at Channel.emit (events.js:182:13)
> at addChunk (_stream_readable.js:283:12) code: 4, lang: '' }

你是使用文件夹传输的那个API了么？我之前使用的时候发现，文件夹里有一些md格式的文件时就会报错，似乎是底层转换为流的时候出错了，当时没有详细研究，只是采用archiver模块压缩出zip后单文件上传来解决。
